FROM php:8.4-apache

WORKDIR /var/www/html

COPY index.php /var/www/html
COPY conexao.php /var/www/html

RUN apt-get update && apt-get install -y \
    libzip-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    zip \
    unzip \
    git \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install install -j$(nproc) gd \
    && docker-php-ext-install gd zip pdo pdo_mysql \
    && docker-php-ext-install mysqli

EXPOSE 80